import { describe, test, expect } from 'bun:test'
import { generateHtml } from './html'
import type { FlakyPattern } from '@flaky-tests/core'

function makePattern(overrides: Partial<FlakyPattern> = {}): FlakyPattern {
  return {
    testFile: 'src/math.test.ts',
    testName: 'adds numbers correctly',
    recentFails: 3,
    priorFails: 0,
    failureKinds: ['assertion'],
    lastErrorMessage: 'Expected 4 but received 5',
    lastErrorStack: 'at Object.<anonymous> (src/math.test.ts:5:3)',
    lastFailed: '2025-01-15T09:30:00.000Z',
    ...overrides,
  }
}

describe('generateHtml', () => {
  test('returns a complete HTML document', () => {
    const html = generateHtml([makePattern()], 7)
    expect(html).toStartWith('<!DOCTYPE html>')
    expect(html).toContain('</html>')
  })

  test('includes pattern count in page header', () => {
    const html = generateHtml([makePattern(), makePattern()], 7)
    expect(html).toContain('2 new patterns detected')
  })

  test('uses singular when one pattern', () => {
    const html = generateHtml([makePattern()], 7)
    expect(html).toContain('1 new pattern detected')
  })

  test('includes window days in summary', () => {
    const html = generateHtml([makePattern()], 14)
    expect(html).toContain('window: 14d')
  })

  test('escapes HTML special characters in test name', () => {
    const html = generateHtml([makePattern({ testName: '<script>alert("xss")</script>' })], 7)
    expect(html).toContain('&lt;script&gt;alert(&quot;xss&quot;)&lt;/script&gt;')
    expect(html).not.toContain('<script>alert("xss")</script>')
  })

  test('escapes HTML special characters in test file', () => {
    const html = generateHtml([makePattern({ testFile: 'src/<weird>&file.ts' })], 7)
    expect(html).toContain('src/&lt;weird&gt;&amp;file.ts')
  })

  test('renders failure count and kinds', () => {
    const html = generateHtml([makePattern({ recentFails: 5, failureKinds: ['timeout', 'assertion'] })], 7)
    expect(html).toContain('5 in 7d')
    expect(html).toContain('timeout, assertion')
  })

  test('omits last error line when lastErrorMessage is null', () => {
    const html = generateHtml([makePattern({ lastErrorMessage: null })], 7)
    expect(html).not.toContain('Last error')
  })

  test('includes last error first line when present', () => {
    const html = generateHtml([makePattern({ lastErrorMessage: 'line one\nline two\nline three' })], 7)
    expect(html).toContain('line one')
  })

  test('renders multiple pattern cards', () => {
    const patterns = [
      makePattern({ testName: 'test-alpha' }),
      makePattern({ testName: 'test-beta' }),
      makePattern({ testName: 'test-gamma' }),
    ]
    const html = generateHtml(patterns, 7)
    expect(html).toContain('id="pattern-1"')
    expect(html).toContain('id="pattern-2"')
    expect(html).toContain('id="pattern-3"')
    expect(html).toContain('test-alpha')
    expect(html).toContain('test-beta')
    expect(html).toContain('test-gamma')
  })

  test('includes copy button with prompt data', () => {
    const html = generateHtml([makePattern()], 7)
    expect(html).toContain('class="copy-btn"')
    expect(html).toContain('data-prompt=')
    expect(html).toContain('copyPrompt(this)')
  })

  test('includes footer with attribution', () => {
    const html = generateHtml([makePattern()], 7)
    expect(html).toContain('Generated by')
    expect(html).toContain('flaky-tests')
  })
})
